import imageSrc from "../assets/restaurant/pizza.jpg";
const restaurantData = [
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "Perú",
    state: "Lima",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4.5,
    reviewCount: 90,
  },
];

export default restaurantData;
